/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.burger;

public class App {

    public static void main(String[] args) {
        //Creo el primer producto
        App.print("--------------Primer Plato ------------\n");
        Dish burger = new Dish("Krabby Patty",1.25);
        burger.display();
        App.print("--------------Añadimos extra ------------\n");
        Extra cheese = new Extra("Cheese",0.25);
        cheese.display();
        App.print("--------------Añadimos el extra al plato ------------\n");
        burger.addExtra(cheese);
        burger.display();
        Dish fries = new Dish("Coral bits",1.0);
        Extra medium = new Extra("Medium", 0.5);
        Extra large = new Extra("Large", 1.0);
        fries.addExtra(medium);
        burger.addExtra(large);
        App.print("--------------Hacemos un pedido------------\n");
        Order myOrder = new Order();
        myOrder.addDish(burger);
        myOrder.addDish(fries);
        myOrder.display();

    }

    public static void print(String string){
        System.out.println(string);
    }
}
