/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.burger;

public class App {

    public static void main(String[] args) {
        //Creo el primer producto
        Dish burger = new Dish("Krabby Patty",1.25);
        burger.display();
        Extra cheese = new Extra("Cheese",0.25);
        cheese.display();
    }
}
